stages:
  prepare:
    cmd: python prepare.py
    deps:
    - data/vineyard_weather_1948-2017.csv
    - prepare.py
    outs:
    - data/prepared.csv
  featurize:
    cmd: python featurize.py
    deps:
    - data/prepared.csv
    - featurize.py
    outs:
    - data/test_data.csv
    - data/train_data.csv
  train:
    cmd: python train.py
    deps:
    - data/train_data.csv
    - params.yaml
    - train.py
    outs:
    - model/model.pkl
  evaluate:
    cmd: python evaluate.py
    deps:
    - data/test_data.csv
    - evaluate.py
    - model/model.pkl
    - params.yaml
    outs:
    - results/evaluation_report.txt
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
