stages:
  prepare:
    cmd: python prepare.py
    deps:
    - data/vineyard_weather_1948-2017.csv
    - prepare.py
    outs:
    - data/prepared.csv
  featurize:
    cmd: python featurize.py
    deps:
    - data/prepared.csv
    - featurize.py
    outs:
    - data/train_data.csv,data/test_data.csv
  train:
    cmd: python train.py
    deps:
    - data/train_data.csv
    - train.py
    outs:
    - model/model.pkl
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
