model:
  type: 'random_forest'  # Can be 'logistic_regression', 'random_forest', 'gradient_boosting'
  params:
    logistic_regression:
      C: 1.0
      solver: 'saga'  # Options: 'liblinear', 'lbfgs', 'saga'
    random_forest:
      n_estimators: 100
      max_depth: null
    gradient_boosting:
      learning_rate: 0.1
      n_estimators: 100
